// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: car_search_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand        string        `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Body         string        `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Year         uint32        `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Color        string        `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Country      string        `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Engine       *Engine       `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"`
	Transmission *Transmission `protobuf:"bytes,8,opt,name=transmission,proto3" json:"transmission,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_search_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_car_search_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_car_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Filter) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Filter) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Filter) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Filter) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Filter) GetEngine() *Engine {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *Filter) GetTransmission() *Transmission {
	if x != nil {
		return x.Transmission
	}
	return nil
}

type SearchCarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SearchCarRequest) Reset() {
	*x = SearchCarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_search_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCarRequest) ProtoMessage() {}

func (x *SearchCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_car_search_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCarRequest.ProtoReflect.Descriptor instead.
func (*SearchCarRequest) Descriptor() ([]byte, []int) {
	return file_car_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchCarRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchCarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car *Car `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
}

func (x *SearchCarResponse) Reset() {
	*x = SearchCarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_search_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCarResponse) ProtoMessage() {}

func (x *SearchCarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_search_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCarResponse.ProtoReflect.Descriptor instead.
func (*SearchCarResponse) Descriptor() ([]byte, []int) {
	return file_car_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchCarResponse) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

var File_car_search_service_proto protoreflect.FileDescriptor

var file_car_search_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x61, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x11,
	0x63, 0x61, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x14, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x06,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x12, 0x34, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2e,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x03, 0x63, 0x61, 0x72, 0x32, 0x50,
	0x0a, 0x10, 0x43, 0x61, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x61, 0x72, 0x6b, 0x68, 0x61, 0x74, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_car_search_service_proto_rawDescOnce sync.Once
	file_car_search_service_proto_rawDescData = file_car_search_service_proto_rawDesc
)

func file_car_search_service_proto_rawDescGZIP() []byte {
	file_car_search_service_proto_rawDescOnce.Do(func() {
		file_car_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_search_service_proto_rawDescData)
	})
	return file_car_search_service_proto_rawDescData
}

var file_car_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_car_search_service_proto_goTypes = []interface{}{
	(*Filter)(nil),            // 0: pb.Filter
	(*SearchCarRequest)(nil),  // 1: pb.SearchCarRequest
	(*SearchCarResponse)(nil), // 2: pb.SearchCarResponse
	(*Engine)(nil),            // 3: pb.Engine
	(*Transmission)(nil),      // 4: pb.Transmission
	(*Car)(nil),               // 5: pb.Car
}
var file_car_search_service_proto_depIdxs = []int32{
	3, // 0: pb.Filter.engine:type_name -> pb.Engine
	4, // 1: pb.Filter.transmission:type_name -> pb.Transmission
	0, // 2: pb.SearchCarRequest.filter:type_name -> pb.Filter
	5, // 3: pb.SearchCarResponse.car:type_name -> pb.Car
	1, // 4: pb.CarSearchService.SearchCar:input_type -> pb.SearchCarRequest
	2, // 5: pb.CarSearchService.SearchCar:output_type -> pb.SearchCarResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_car_search_service_proto_init() }
func file_car_search_service_proto_init() {
	if File_car_search_service_proto != nil {
		return
	}
	file_car_message_proto_init()
	file_engine_message_proto_init()
	file_transmission_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_car_search_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_search_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_search_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_search_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_car_search_service_proto_goTypes,
		DependencyIndexes: file_car_search_service_proto_depIdxs,
		MessageInfos:      file_car_search_service_proto_msgTypes,
	}.Build()
	File_car_search_service_proto = out.File
	file_car_search_service_proto_rawDesc = nil
	file_car_search_service_proto_goTypes = nil
	file_car_search_service_proto_depIdxs = nil
}
