// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: engine_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Engine_Type int32

const (
	Engine_V2  Engine_Type = 0
	Engine_V4  Engine_Type = 1
	Engine_V6  Engine_Type = 2
	Engine_V8  Engine_Type = 4
	Engine_V10 Engine_Type = 5
	Engine_V12 Engine_Type = 6
)

// Enum value maps for Engine_Type.
var (
	Engine_Type_name = map[int32]string{
		0: "V2",
		1: "V4",
		2: "V6",
		4: "V8",
		5: "V10",
		6: "V12",
	}
	Engine_Type_value = map[string]int32{
		"V2":  0,
		"V4":  1,
		"V6":  2,
		"V8":  4,
		"V10": 5,
		"V12": 6,
	}
)

func (x Engine_Type) Enum() *Engine_Type {
	p := new(Engine_Type)
	*p = x
	return p
}

func (x Engine_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Engine_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_message_proto_enumTypes[0].Descriptor()
}

func (Engine_Type) Type() protoreflect.EnumType {
	return &file_engine_message_proto_enumTypes[0]
}

func (x Engine_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Engine_Type.Descriptor instead.
func (Engine_Type) EnumDescriptor() ([]byte, []int) {
	return file_engine_message_proto_rawDescGZIP(), []int{0, 0}
}

type Engine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         Engine_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Engine_Type" json:"type,omitempty"`
	Displacement float64     `protobuf:"fixed64,2,opt,name=displacement,proto3" json:"displacement,omitempty"`
	FuelType     string      `protobuf:"bytes,3,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Horsepower   uint32      `protobuf:"varint,4,opt,name=horsepower,proto3" json:"horsepower,omitempty"`
	Torque       uint32      `protobuf:"varint,5,opt,name=torque,proto3" json:"torque,omitempty"`
}

func (x *Engine) Reset() {
	*x = Engine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Engine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Engine) ProtoMessage() {}

func (x *Engine) ProtoReflect() protoreflect.Message {
	mi := &file_engine_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Engine.ProtoReflect.Descriptor instead.
func (*Engine) Descriptor() ([]byte, []int) {
	return file_engine_message_proto_rawDescGZIP(), []int{0}
}

func (x *Engine) GetType() Engine_Type {
	if x != nil {
		return x.Type
	}
	return Engine_V2
}

func (x *Engine) GetDisplacement() float64 {
	if x != nil {
		return x.Displacement
	}
	return 0
}

func (x *Engine) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *Engine) GetHorsepower() uint32 {
	if x != nil {
		return x.Horsepower
	}
	return 0
}

func (x *Engine) GetTorque() uint32 {
	if x != nil {
		return x.Torque
	}
	return 0
}

var File_engine_message_proto protoreflect.FileDescriptor

var file_engine_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe0, 0x01, 0x0a, 0x06, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x75, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68,
	0x6f, 0x72, 0x73, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x6f, 0x72, 0x71, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x6f, 0x72,
	0x71, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x56,
	0x32, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x34, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x56,
	0x36, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x38, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x56,
	0x31, 0x30, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x31, 0x32, 0x10, 0x06, 0x42, 0x1d, 0x5a,
	0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x6b,
	0x68, 0x61, 0x74, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_message_proto_rawDescOnce sync.Once
	file_engine_message_proto_rawDescData = file_engine_message_proto_rawDesc
)

func file_engine_message_proto_rawDescGZIP() []byte {
	file_engine_message_proto_rawDescOnce.Do(func() {
		file_engine_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_message_proto_rawDescData)
	})
	return file_engine_message_proto_rawDescData
}

var file_engine_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_engine_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engine_message_proto_goTypes = []interface{}{
	(Engine_Type)(0), // 0: pb.Engine.Type
	(*Engine)(nil),   // 1: pb.Engine
}
var file_engine_message_proto_depIdxs = []int32{
	0, // 0: pb.Engine.type:type_name -> pb.Engine.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engine_message_proto_init() }
func file_engine_message_proto_init() {
	if File_engine_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Engine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_message_proto_goTypes,
		DependencyIndexes: file_engine_message_proto_depIdxs,
		EnumInfos:         file_engine_message_proto_enumTypes,
		MessageInfos:      file_engine_message_proto_msgTypes,
	}.Build()
	File_engine_message_proto = out.File
	file_engine_message_proto_rawDesc = nil
	file_engine_message_proto_goTypes = nil
	file_engine_message_proto_depIdxs = nil
}
