// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: transmission_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transmission_Type int32

const (
	Transmission_Manual    Transmission_Type = 0
	Transmission_Automatic Transmission_Type = 1
)

// Enum value maps for Transmission_Type.
var (
	Transmission_Type_name = map[int32]string{
		0: "Manual",
		1: "Automatic",
	}
	Transmission_Type_value = map[string]int32{
		"Manual":    0,
		"Automatic": 1,
	}
)

func (x Transmission_Type) Enum() *Transmission_Type {
	p := new(Transmission_Type)
	*p = x
	return p
}

func (x Transmission_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transmission_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_transmission_message_proto_enumTypes[0].Descriptor()
}

func (Transmission_Type) Type() protoreflect.EnumType {
	return &file_transmission_message_proto_enumTypes[0]
}

func (x Transmission_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transmission_Type.Descriptor instead.
func (Transmission_Type) EnumDescriptor() ([]byte, []int) {
	return file_transmission_message_proto_rawDescGZIP(), []int{0, 0}
}

type Transmission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  Transmission_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Transmission_Type" json:"type,omitempty"`
	Gears uint32            `protobuf:"varint,2,opt,name=gears,proto3" json:"gears,omitempty"`
}

func (x *Transmission) Reset() {
	*x = Transmission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transmission_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transmission) ProtoMessage() {}

func (x *Transmission) ProtoReflect() protoreflect.Message {
	mi := &file_transmission_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transmission.ProtoReflect.Descriptor instead.
func (*Transmission) Descriptor() ([]byte, []int) {
	return file_transmission_message_proto_rawDescGZIP(), []int{0}
}

func (x *Transmission) GetType() Transmission_Type {
	if x != nil {
		return x.Type
	}
	return Transmission_Manual
}

func (x *Transmission) GetGears() uint32 {
	if x != nil {
		return x.Gears
	}
	return 0
}

var File_transmission_message_proto protoreflect.FileDescriptor

var file_transmission_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x72, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x65, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x65, 0x61, 0x72,
	0x73, 0x22, 0x21, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61, 0x6e,
	0x75, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74,
	0x69, 0x63, 0x10, 0x01, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x6b, 0x68, 0x61, 0x74, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x41,
	0x75, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transmission_message_proto_rawDescOnce sync.Once
	file_transmission_message_proto_rawDescData = file_transmission_message_proto_rawDesc
)

func file_transmission_message_proto_rawDescGZIP() []byte {
	file_transmission_message_proto_rawDescOnce.Do(func() {
		file_transmission_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_transmission_message_proto_rawDescData)
	})
	return file_transmission_message_proto_rawDescData
}

var file_transmission_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transmission_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transmission_message_proto_goTypes = []interface{}{
	(Transmission_Type)(0), // 0: pb.Transmission.Type
	(*Transmission)(nil),   // 1: pb.Transmission
}
var file_transmission_message_proto_depIdxs = []int32{
	0, // 0: pb.Transmission.type:type_name -> pb.Transmission.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transmission_message_proto_init() }
func file_transmission_message_proto_init() {
	if File_transmission_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transmission_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transmission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transmission_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transmission_message_proto_goTypes,
		DependencyIndexes: file_transmission_message_proto_depIdxs,
		EnumInfos:         file_transmission_message_proto_enumTypes,
		MessageInfos:      file_transmission_message_proto_msgTypes,
	}.Build()
	File_transmission_message_proto = out.File
	file_transmission_message_proto_rawDesc = nil
	file_transmission_message_proto_goTypes = nil
	file_transmission_message_proto_depIdxs = nil
}
